### ISSUE TITLE
Is the ports in docker-composer.yml used?

### ISSUE THREAD

**Issue by andertun** [magento/magento2devbox-web#100]
Even though I follow the guide here to **[set static ports](http://devdocs.magento.com/guides/v2.1/install-gde/docker/docker-ref.html#devbox-static-port)**. I get random ports every time.

```
ports:
  - "33333:80"
  - "22222:22"
```

I can see in the output of the `m2devbox-init.sh` script that the `33333` port was used.

**Output from `m2devbox-init.sh`** :

> cd /var/www/magento2 && php bin/magento setup:install --base-url=**http://127.0.0.1:33333/** --db-host=db --db-name=magento2 --db-user=root --db-password=root --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com --admin-user=admin --admin-password=admin123 --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1 --backend-frontname=admin
> .
> .
> To open installed magento go to **http://127.0.0.1:32794**, admin area: http://127.0.0.1:32794/admin, login: admin, password: admin123

Why didn't I get port `33333`?

And yes, I have also tried `./m2devbox-reset.sh`.

**Comment by duythien** [comment]
If you want use port 3333 you should defined at varnish 

```
varnish:
        container_name: magento2devbox_varnish_2f51672e0d8141e2f2f14ff91debc424
        restart: 'no'
        depends_on:
          - "web"
        image: magento/magento2devbox-varnish:latest
        ports:
          - "33333:6081"
```
