### ISSUE TITLE
Can use port 80 for vanish?

### ISSUE THREAD

**Issue by duythien** [magento/magento2devbox-web#101]
I have try config to use http://localhost instate of use http://locahost:8080 or some thing port

```
##
# Services needed to run Magento2 application on Docker
#
# Docker Compose defines required services and attach them together through aliases
##
version: '2'
services:
    web:
        container_name: magento2devbox_web_2f51672e0d8141e2f2f14ff91debc424
        restart: 'no'
        image: magento/magento2devbox-web:latest
        volumes:
          - ./magento2:/var/www/magento2
          - "~/.composer:/home/magento2/.composer"
          - "~/.ssh:/home/magento2/.ssh"
          - "./shared/logs/apache2:/var/log/apache2"
          - "./shared/logs/php-fpm:/var/log/php-fpm"
          - "./shared/.magento-cloud:/home/magento2/.magento-cloud"
        environment:
          - USE_SHARED_WEBROOT=0
          - SHARED_CODE_PATH="/home/magento2/magento2"
          - USE_RABBITMQ=1
          - USE_REDIS_FULL_PAGE_CACHE=1
          - USE_REDIS_CACHE=1
          - USE_REDIS_SESSIONS=1
          - USE_VARNISH=1
          - USE_ELASTICSEARCH=1
          - MAGENTO_PUBLIC_KEY=
          - MAGENTO_PRIVATE_KEY=
          - MAGENTO_USE_SOURCES_IN_HOST=1
          - CREATE_SYMLINK_EE=0
          - HOST_CE_PATH=/Users/phanbook/github/magento2/magento2
          - EE_DIRNAME=magento2ee
          - MAGENTO_DOWNLOAD_SOURCES_COMPOSER=0
          - MAGENTO_EDITION=
          - MAGENTO_VERSION=2.1.6
          - MAGENTO_SAMPLE_DATA_INSTALL=0
          - MAGENTO_DOWNLOAD_SOURCES_CLOUD=0
          - MCLOUD_USERNAME=
          - MCLOUD_PASSWORD=
          - MCLOUD_GENERATE_NEW_TOKEN=
          - MCLOUD_PROJECT=
          - MCLOUD_BRANCH=
          - MAGENTO_CRON_RUN=0
          - MAGENTO_DI_COMPILE=0
          - MAGENTO_GRUNT_COMPILE=0
          - MAGENTO_STATIC_CONTENTS_DEPLOY=0
          - MAGENTO_BACKEND_PATH=admin
          - MAGENTO_ADMIN_USER=admin
          - MAGENTO_ADMIN_PASSWORD=admin123
        ports:
          - "8080:80"
          - "22:22"

    db:
        container_name: magento2devbox_db_2f51672e0d8141e2f2f14ff91debc424
        restart: 'no'
        image: mysql:5.6
        ports:
          - "3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=magento2
        volumes:
          - "./shared/db:/var/lib/mysql"
          - "./shared/var/logs/mysql:/var/log/mysql"

    varnish:
        container_name: magento2devbox_varnish_2f51672e0d8141e2f2f14ff91debc424
        restart: 'no'
        depends_on:
          - "web"
        image: magento/magento2devbox-varnish:latest
        ports:
          - "80:6081"

    redis:
        container_name: magento2devbox_redis_2f51672e0d8141e2f2f14ff91debc424
        restart: 'no'
        image: redis:3.0.7

    rabbit:
        container_name: magento2devbox_rabbit_2f51672e0d8141e2f2f14ff91debc424
        restart: 'no'
        image: rabbitmq:3-management
        ports:
          - "15672"
          - "5672"

    elasticsearch:
        container_name: magento2devbox_elastic_2f51672e0d8141e2f2f14ff91debc424
        restart: 'no'
        image: elasticsearch:2
        ports:
          - "9200"

```

When I running ./m2devbox-init.sh after few minute I get error below

```
config
layout
block_html
collections
reflection
db_ddl
eav
customer_notification
full_page
config_integration
config_integration_api
translate
config_webservice
Executing shell command:
sudo service apache2 restart
Restarting web server: apache2AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.5. Set the 'ServerName' directive globally to suppress this message
(98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
 failed!
The apache2 instance did not start within 20 seconds. Please read the log files to discover problems ... (warning).

                             
  [Exception]                
  Command failed to execute  
```
Maybe you should default port apache at /etc/apache2/ports.conf ? any idea to running http://localhost

**Comment by duythien** [comment]
Ok Now I just use option volumes in compose so that it will working file 

```
     restart: 'no'
        image: magento/magento2devbox-web:latest
        volumes:
          - ./magento2:/var/www/magento2
          - ./conf/apache/ports.conf:/etc/apache2/ports.conf
```
And ports.conf

```
# If you just change the port or add more ports here, you will likely also
# have to change the VirtualHost statement in
# /etc/apache2/sites-enabled/000-default.conf

Listen 8080

<IfModule ssl_module>
        Listen 443
</IfModule>

<IfModule mod_gnutls.c>
        Listen 443
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```
Just share I want to do it
