### ISSUE TITLE
Move DOCUMENT_ROOT to pub/

### ISSUE THREAD

**Issue by Vinai** [magento/magento2devbox-web#75]
The recommended setup for serious installations is to use pub/ as the web server document root, as it reduces the attack surface.  
If the devbox also used pub/ as the document root it would be closer to what is a real project development environment.

**Comment by astragt** [comment]
Do you know if there is any temporary fix for the meantime?

**Comment by jacquesbh** [comment]
@astragt you can do that:

Update the `docker-compose.yml` to change the image `web`.
From something like this:
```yaml
services:
    web:
        container_name: magento2devbox_web_c3d52f7194349d5d6c904ed3b0939750
        restart: always
        image: magento/magento2devbox-web:latest
```
To this:
```yaml
services:
    web:
        container_name: magento2devbox_web_c3d52f7194349d5d6c904ed3b0939750
        restart: always
        build: web/
```
Then where your `docker-compose.yml` is you can create a directory name `web/` and put a `Dockerfile` in it with the following content:

```Dockerfile
FROM magento/magento2devbox-web:latest

RUN configfile=/etc/apache2/sites-enabled/apache-default.conf; \
    sed 's/\/var\/www\/magento2/\/var\/www\/magento2\/web/' $configfile | tee $configfile
```

Then it should work.
